auditConfig:
  ignoreGhsas:
    - GHSA-mh99-v99m-4gvg
    - GHSA-qwww-vcr4-c8h2

onlyBuiltDependencies: []

overrides:
  brace-expansion@5.0.7: 5.0.8
  postcss: 8.5.18

peerDependencyRules:
  allowedVersions:
    eslint-plugin-import>eslint: '9'
    eslint-plugin-jsx-a11y>eslint: '9'
