auditConfig:
  ignoreGhsas:
    - GHSA-mh99-v99m-4gvg

onlyBuiltDependencies: []

overrides:
  source-map-js: '>=1.2.2'

peerDependencyRules:
  allowedVersions:
    eslint-plugin-import>eslint: '9'
    eslint-plugin-jsx-a11y>eslint: '9'
